### ISSUE TITLE
Altair charts not rendering on github

### ISSUE THREAD

**Issue by Anupriya-Sri** [UBC-MDS/Telco_Customer_Churn_Prediction_Group12#12]
The EDA file is uploaded on github but the charts plotted in altair are not rendering on github. These charts are appearing properly on local. Also, the charts plotted in seaborn and matplotlib are visible on github.

**Comment by jcasoli** [comment]
I think we may just need to add alt.renderers.enable(“mimetype”) to the file

**Comment by adammorphy** [comment]
It's been added and should be rendered correctly now!
