### ISSUE TITLE
How do we want to report coefficients? 

### ISSUE THREAD

**Issue by jcasoli** [UBC-MDS/Telco_Customer_Churn_Prediction_Group12#21]
Do we want the most positively, or negatively correlated coefficients? Or do we want to just report on the highest magnitude (abs value) coefficients?

**Comment by jcasoli** [comment]
@zzhzoe I decided that it was easiest to just save all the feature coefficients to a csv file. You can then read the file in the final report and sort however is required

**Comment by zzhzoe** [comment]
ok, got it.  Feel free to change it.
