### ISSUE TITLE
Do we want to keep the gender feature? 

### ISSUE THREAD

**Issue by jcasoli** [UBC-MDS/Telco_Customer_Churn_Prediction_Group12#24]
I think we should all have some input here... 

My vote would be to drop it, as I think using this feature could lead to some unintended consequences down the line. Please let me know what you think!

**Comment by Anupriya-Sri** [comment]
Agreed. The churn data and features impacting churn are used by companies to develop the marketing strategy and released customized offer. By including gender as a feature, we would add a bias to the models which may not be correct. So, we should drop this column for transformation and predictions.

**Comment by jcasoli** [comment]
the group has agreed to drop the gender feature in the preprocessing script.

**Comment by zzhzoe** [comment]
Agree with drop the gender feature in the preprocessing script.
