### ISSUE TITLE
Project environment

### ISSUE THREAD

**Issue by Anupriya-Sri** [UBC-MDS/Telco_Customer_Churn_Prediction_Group12#27]
Hi, should we create a separate .yaml file with project dependencies? I think it would be required if someone wants to run the project later on.

**Comment by jcasoli** [comment]
I'm fairly certain that this will be a part of the later requirements of the project. I believe we are going to use docker to do this.

**Comment by adammorphy** [comment]
The environment file with all dependencies has been added. Regardless of if its needed it will be nice to have, ensuring everyone can run all scripts.
