### ISSUE TITLE
EDA saving altair plots

### ISSUE THREAD

**Issue by Anupriya-Sri** [UBC-MDS/Telco_Customer_Churn_Prediction_Group12#32]
The EDA notebook and script is updated but I am not able to save the plots created in altair. I have downgraded the jsonschema package, installed altair_saver, included mimetype. But the figures are still not getting saved on my system.

**Comment by adammorphy** [comment]
I added a repo environment which should fix any issues with your package versions. Alt air plots are now able to render and save.
